### ISSUE TITLE
Change setAttributes and listener to async

### ISSUE THREAD

**Issue by ldvlgr** [lhamoudi/plugin-log-hang-up-by#1]
Task.setAttributes returns a promise, 
https://twilio.github.io/twilio-taskrouter.js/Task.html#setAttributes__anchor

so it's probably better to make this async/await:

```
async persistTaskAttributes(task) {
    if (!('conversations' in task.attributes)) {
      task.attributes.conversations = {};
    }
    if (this.callState.hangUpBy) {
      task.attributes.conversations.hang_up_by = this.callState.hangUpBy;
      // TODO: Maybe we can include preceded_by and followed_by - for tracking transfers
    }
    await task.setAttributes(task.attributes);
```
    
    and make the listener async
    
   ```
 flex.Actions.addListener("beforeCompleteTask", async (payload) => {
      await this.persistTaskAttributes(payload.task);
      this.resetCallState();
    });
```

**Comment by lhamoudi** [comment]
Agreed, and resolved. [Commit](https://github.com/lhamoudi/plugin-log-hang-up-by/commit/43ea0f84ac148c735f06c715551b4c9dd7cbf01d)

**Comment by lhamoudi** [comment]
And the other part: https://github.com/lhamoudi/plugin-log-hang-up-by/commit/71709382a8e30d03898e0d00958e067869d869e7
